# Generated by Django 5.0 on 2023-12-23 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysGestion', '0004_medecin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medecin',
            name='heures_disponibilite',
        ),
        migrations.AlterField(
            model_name='medecin',
            name='adresse_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
