# Generated by Django 5.0 on 2023-12-23 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysGestion', '0006_rendezvous'),
    ]

    operations = [
        migrations.CreateModel(
            name='DossierMedical',
            fields=[
                ('dossier_id', models.AutoField(primary_key=True, serialize=False)),
                ('date_creation', models.DateField(auto_now_add=True)),
                ('informations_medicales', models.TextField(blank=True, null=True)),
                ('resultats_examens', models.TextField(blank=True, null=True)),
                ('traitement_en_cours', models.TextField(blank=True, null=True)),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysGestion.medecin')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysGestion.patient')),
            ],
        ),
    ]
