# Generated by Django 5.0 on 2023-12-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysGestion', '0007_dossiermedical'),
    ]

    operations = [
        migrations.CreateModel(
            name='Departement',
            fields=[
                ('departement_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(choices=[('Cardiologie', 'Cardiologue'), ('Neurologie', 'Neurologue'), ('Urologie', 'Urologue'), ('Rhumatologie', 'Rhumatologue'), ('ORL', 'ORL')], max_length=20),
        ),
    ]
