# Generated by Django 5.0 on 2023-12-23 14:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysGestion', '0009_departement_nom'),
    ]

    operations = [
        migrations.CreateModel(
            name='TacheDepartement',
            fields=[
                ('tache_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('terminee', 'Terminée'), ('en_attente', 'En attente')], max_length=20)),
                ('departement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysGestion.departement')),
                ('medecin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sysGestion.medecin')),
            ],
        ),
    ]
