# Generated by Django 5.0 on 2024-01-21 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sysGestion', '0010_tachedepartement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(blank=True, choices=[('Cardiologie', 'Cardiologie')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medecin',
            name='specialite',
            field=models.CharField(choices=[('Cardiologie', 'Cardiologue')], max_length=20),
        ),
    ]
