# Generated by Django 5.0.1 on 2024-01-25 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysGestion', '0011_alter_departement_nom_alter_medecin_specialite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='id',
            new_name='patient_id',
        ),
    ]
