# Generated by Django 5.0.1 on 2024-01-25 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sysGestion', '0012_rename_id_patient_patient_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rendezvous',
            old_name='statut',
            new_name='status',
        ),
    ]
